---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-api-gateway
  namespace: davidyu
spec:
  selector:
    matchLabels:
      type:  msa-api-gateway
      app: msa-api-gateway
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type:  msa-api-gateway
        app: msa-api-gateway
    spec:
      containers:
        - name:  msa-api-gateway
          image: ygygood/msa-api-gateway:3.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: msa-api-gateway
  namespace: davidyu
spec:
  type: NodePort
  selector:
    app: msa-api-gateway
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 19800

