---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-service-discovery
  namespace: davidyu
spec:
  selector:
    matchLabels:
      type:  msa-service-discovery
      app: msa-service-discovery
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type:  msa-service-discovery
        app: msa-service-discovery
    spec:
      containers:
        - name:  msa-service-discovery
          image: ygygood/msa-service-discovery:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-discovery
  namespace: davidyu
spec:
  type: NodePort
  selector:
    app: msa-service-discovery
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
      nodePort: 19001

