### CREATE USER
POST http://{{address}}/user-service/users
Content-Type: application/json

{
  "email" : "ygygood@naver.com",
  "name" : "davidyu",
  "pwd" : "!admin1234"
}

### LOGIN
POST http://{{address}}/user-service/login
Content-Type: application/json

{
  "email" : "ygygood@naver.com",
  "pwd" : "!admin1234"
}

### RETRIEVE USERS
GET http://{{address}}/user-service/users
Content-Type: application/json
Authorization: {{jwtToken}}

#CATALOG SERVICE
### RETRIEVE CATALOGS
GET http://{{address}}/catalog-service/catalogs
Content-Type: application/json
Authorization: {{jwtToken}}

#ORDER SERVICE

### Health Check
GET http://{{address}}/order-service/health_check
Content-Type: application/json
Authorization: {{jwtToken}}

### ORDER
POST http://{{address}}/order-service/3884294c-944e-44c2-954d-4de89a3dc563/orders
Content-Type: application/json
Authorization: {{jwtToken}}

{
  "productId": "CATALOG-002",
  "qty": 10,
  "unitPrice": 900
}

### ORDER RETRIEVE
GET http://{{address}}/order-service/3884294c-944e-44c2-954d-4de89a3dc563/orders
Content-Type: application/json
Authorization: {{jwtToken}}

### KAFKA Sync Connector
GET http://10.81.208.54:/connectors

{
    "name":"my-sink-connect",
    "config":{
        "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
        "connection.url":"jdbc:mysql://localhost:13306/mydb",
        "connection.user":"root",
        "connection.password":"test1234",
        "auto.create":"true",
        "auto.evolve":"true",
        "delete.enabled":"false",
        "tasks.max":"1",
        "topics":"my_topic_users"
    }
}
