### CREATE USER
POST http://{{address}}/user-service/users
Content-Type: application/json

{
  "email" : "ygygood10@lgcns.com",
  "name" : "davidyu",
  "pwd" : "!admin1234"
}

### LOGIN
POST http://{{address}}/user-service/login
Content-Type: application/json

{
  "email" : "ygygood10@lgcns.com",
  "pwd" : "!admin1234"
}

### RETRIEVE USERS
GET http://{{address}}/user-service/users
Content-Type: application/json
Authorization: {{jwtToken}}

#CATALOG SERVICE
### RETRIEVE CATALOGS
GET http://{{address}}/catalog-service/catalogs
Content-Type: application/json
Authorization: {{jwtToken}}

#ORDER SERVICE

### Health Check
GET http://{{address}}/order-service/health_check
Content-Type: application/json
Authorization: {{jwtToken}}

### ORDER
POST http://{{address}}/order-service/a960a0a9-7960-4795-aef0-2099e13eaad6/orders
Content-Type: application/json
Authorization: {{jwtToken}}

{
  "productId": "CATALOG-002",
  "qty": 10,
  "unitPrice": 900
}

### ORDER RETRIEVE
GET http://{{address}}/order-service/a960a0a9-7960-4795-aef0-2099e13eaad6/orders
Content-Type: application/json
Authorization: {{jwtToken}}