---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-catalog-service
  namespace: davidyu
spec:
  selector:
    matchLabels:
      app: msa-catalog-service
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: msa-catalog-service
        app:  msa-catalog-service
    spec:
      containers:
        - name: msa-catalog-service
          image: ygygood/msa-catalog-service:3.3
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: msa-catalog-service
  namespace: davidyu
spec:
  selector:
    app: msa-catalog-service
  ports:
    - port: 9002
      targetPort: 9002
  type: ClusterIP
